#!/usr/bin/env bash
set -euo pipefail

# MultiMax - Setup/Update script for VPS (Linux)
# - Installs system packages required by Python libs (matplotlib, reportlab, psycopg)
# - Creates/updates virtualenv and installs Python dependencies
# - Generates a default .env.txt pointing DATA_DIR to the RAID folder
# Usage:
#   cd /path/to/MultiMax
#   ./scripts/vps_setup.sh [/path/to/raid]
#
# If no RAID path is provided, defaults to "./raid" inside the project.

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PARENT_ROOT="$(cd "${PROJECT_ROOT}/.." && pwd)"
RAID_DIR="${1:-${PARENT_ROOT}/multimax-raid}"
ENV_FILE="${PROJECT_ROOT}/.env.txt"
VENV_DIR="${PROJECT_ROOT}/.venv"
REQ_FILE="${PROJECT_ROOT}/requirements.txt"

echo "==> MultiMax VPS Setup"
echo "Project root: ${PROJECT_ROOT}"
echo "RAID dir: ${RAID_DIR}"

mkdir -p "${RAID_DIR}"
mkdir -p "${RAID_DIR}/data"

have_cmd() { command -v "$1" >/dev/null 2>&1; }

install_apt() {
  echo "==> Detected apt (Debian/Ubuntu). Installing system packages..."
  sudo apt-get update -y
  sudo apt-get install -y \
    python3 python3-venv python3-dev \
    build-essential git tzdata pkg-config \
    libpq-dev \
    libjpeg-dev libpng-dev libfreetype6-dev \
    ghostscript fonts-dejavu-core
}

install_dnf() {
  echo "==> Detected dnf (Fedora/RHEL). Installing system packages..."
  sudo dnf install -y \
    python3 python3-venv python3-devel \
    gcc gcc-c++ make git tzdata \
    postgresql-devel \
    libjpeg-turbo-devel libpng-devel freetype-devel \
    ghostscript dejavu-sans-fonts pkgconf-pkg-config
}

install_yum() {
  echo "==> Detected yum (CentOS/RHEL). Installing system packages..."
  sudo yum install -y \
    python3 python3-virtualenv python3-devel \
    gcc gcc-c++ make git tzdata \
    postgresql-devel \
    libjpeg-turbo-devel libpng-devel freetype-devel \
    ghostscript dejavu-sans-fonts pkgconf-pkg-config
}

if have_cmd apt-get; then
  install_apt
elif have_cmd dnf; then
  install_dnf
elif have_cmd yum; then
  install_yum
else
  echo "WARN: No supported package manager found (apt/dnf/yum). Skipping system package installation."
fi

python3_bin="python3"
if ! have_cmd "${python3_bin}"; then
  echo "ERROR: python3 not found. Please install Python 3.10+ and rerun."
  exit 1
fi

echo "==> Creating/Updating virtualenv at ${VENV_DIR}"
if [ ! -d "${VENV_DIR}" ]; then
  "${python3_bin}" -m venv "${VENV_DIR}"
fi
source "${VENV_DIR}/bin/activate"
python -m pip install --upgrade pip wheel setuptools

if [ ! -f "${REQ_FILE}" ]; then
  echo "ERROR: requirements.txt not found at ${REQ_FILE}"
  exit 1
fi

echo "==> Installing Python dependencies from requirements.txt"
pip install -r "${REQ_FILE}"

echo "==> Preparing environment file at ${ENV_FILE}"
# If there is an existing .env.txt in the project root, copy it EXACTLY
if [ -f "${PROJECT_ROOT}/.env.txt" ]; then
  echo "==> Found existing .env.txt in project root. Copying unchanged..."
  cp "${PROJECT_ROOT}/.env.txt" "${ENV_FILE}"
else
  echo "==> Generating new .env.txt (no local template found)"
  SECRET_KEY_HEX="$(openssl rand -hex 32 2>/dev/null || python - <<'PY'\nimport secrets; print(secrets.token_hex(32))\nPY\n)"
  # Allow fixed secrets via environment variables
  SECRET_KEY_VAL="${SECRET_KEY:-}"
  ADMIN_PWD_VAL="${SENHA_ADMIN:-}"
  OPER_PWD_VAL="${SENHA_OPERADOR:-}"
  DB_PATH="${RAID_DIR}/data/estoque.db"
  cat > "${ENV_FILE}" <<EOF
# MultiMax environment (generated by vps_setup.sh)
HOST=0.0.0.0
PORT=5000
DEBUG=false
SECRET_KEY=${SECRET_KEY_VAL:-${SECRET_KEY_HEX}}
DATA_DIR=${RAID_DIR}/data
SQLALCHEMY_DATABASE_URI=sqlite:///${DB_PATH}
DB_BACKUP_ENABLED=true
FLASK_LOG_LEVEL=INFO
FLASK_LOG_BODY=true
SENHA_ADMIN=${ADMIN_PWD_VAL:-admin123}
SENHA_OPERADOR=${OPER_PWD_VAL:-op123}
EOF
fi

echo "==> Done."
echo "Summary:"
echo " - System packages installed (if supported package manager was found)"
echo " - Virtualenv at: ${VENV_DIR}"
echo " - Dependencies installed from: ${REQ_FILE}"
echo " - Environment file: ${ENV_FILE}"
echo " - Data directory: ${RAID_DIR}/data"
echo ""
echo "To run the app:"
echo "  source \"${VENV_DIR}/bin/activate\" && python app.py"
